import { useMemo, useRef, useState } from 'react';
import { Download, Image as ImageIcon, Loader2, Play, Square } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { generateComfyImage } from '@/lib/comfyApi';

interface ImageGeneratorPageProps {
  initialPrompt: string;
}

const sizes = {
  portrait: { label: 'Portrait 4:5', width: 896, height: 1120 },
  square: { label: 'Square 1:1', width: 1024, height: 1024 },
  reel: { label: 'Reel 9:16', width: 768, height: 1344 },
  landscape: { label: 'Landscape 4:3', width: 1152, height: 864 },
} as const;

type SizeId = keyof typeof sizes;

export function ImageGeneratorPage({ initialPrompt }: ImageGeneratorPageProps) {
  const [prompt, setPrompt] = useState(initialPrompt);
  const [sizeId, setSizeId] = useState<SizeId>('portrait');
  const [status, setStatus] = useState('Ready. ComfyUI Desktop must remain open.');
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const controllerRef = useRef<AbortController | null>(null);
  const size = useMemo(() => sizes[sizeId], [sizeId]);

  const generate = async () => {
    const cleanPrompt = prompt.trim();
    if (!cleanPrompt || generating) return;
    const controller = new AbortController();
    controllerRef.current = controller;
    setGenerating(true);
    setImageUrl(null);

    try {
      const result = await generateComfyImage(
        { prompt: cleanPrompt, width: size.width, height: size.height },
        setStatus,
        controller.signal,
      );
      setImageUrl(result);
    } catch (error) {
      setStatus(
        error instanceof DOMException && error.name === 'AbortError'
          ? 'Generation cancelled.'
          : error instanceof Error
            ? error.message
            : 'Generation failed.',
      );
    } finally {
      controllerRef.current = null;
      setGenerating(false);
    }
  };

  return (
    <div className="h-full flex flex-col">
      <div className="mb-5">
        <h2 className="text-xl font-semibold">Generate Image</h2>
        <p className="text-sm text-muted-foreground mt-1">FLUX.2 Klein 4B · Generated locally on your RTX 4090</p>
      </div>

      <div className="grid min-h-0 flex-1 gap-5 lg:grid-cols-[minmax(320px,460px)_1fr]">
        <section className="rounded-lg border border-border/50 bg-card/50 p-4 flex flex-col gap-4 overflow-y-auto">
          <label className="space-y-2">
            <span className="text-sm font-medium">Image prompt</span>
            <textarea
              value={prompt}
              onChange={(event) => setPrompt(event.target.value)}
              placeholder="Describe the subject, action, environment, lighting, and style…"
              className="min-h-64 w-full resize-y rounded-md border border-border bg-background/60 p-3 text-sm leading-relaxed outline-none focus:border-primary"
            />
          </label>

          <label className="space-y-2">
            <span className="text-sm font-medium">Image shape</span>
            <select
              value={sizeId}
              onChange={(event) => setSizeId(event.target.value as SizeId)}
              disabled={generating}
              className="h-10 w-full rounded-md border border-border bg-background px-3 text-sm"
            >
              {Object.entries(sizes).map(([id, option]) => (
                <option key={id} value={id}>{option.label} · {option.width}×{option.height}</option>
              ))}
            </select>
          </label>

          <div className="flex gap-2">
            <Button onClick={generate} disabled={generating || !prompt.trim()} className="flex-1">
              {generating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Play className="mr-2 h-4 w-4" />}
              {generating ? 'Generating…' : 'Generate'}
            </Button>
            {generating && (
              <Button variant="outline" onClick={() => controllerRef.current?.abort()}>
                <Square className="mr-2 h-4 w-4" />Stop
              </Button>
            )}
          </div>
          <p className="text-xs text-muted-foreground">{status}</p>
        </section>

        <section className="min-h-0 rounded-lg border border-border/50 bg-card/30 p-4 flex items-center justify-center overflow-auto">
          {imageUrl ? (
            <div className="flex h-full w-full flex-col items-center justify-center gap-3">
              <img src={imageUrl} alt="Generated by Galazar" className="max-h-[calc(100%-3rem)] max-w-full rounded-md object-contain shadow-2xl" />
              <Button variant="outline" size="sm" asChild>
                <a href={imageUrl} download="Galazar.png"><Download className="mr-2 h-4 w-4" />Download image</a>
              </Button>
            </div>
          ) : (
            <div className="text-center text-muted-foreground">
              <ImageIcon className="mx-auto mb-3 h-12 w-12 opacity-30" />
              <p className="text-sm">{generating ? 'Your image is being created…' : 'Your finished image will appear here.'}</p>
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
